version: "3.8"

services:
  db:
    image: mysql
    container_name: MYSQL
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - ./arquitectura:/var/lib/mysql
